language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install SQLAlchemy --use-mirrors"
# command to run tests
script: nosetests
env:
  - DB=sqlite
  - DB=postgres
services: postgresql
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS xdapy_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database xdapy_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then mkdir ~/.xdapy; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then echo '[default]' >> ~/.xdapy/engine.ini; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then echo 'url = postgresql://postgres@localhost/xdapy' >> ~/.xdapy/engine.ini; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then echo '[test]' >> ~/.xdapy/engine.ini; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then echo 'url = postgresql://postgres@localhost/xdapy_test' >> ~/.xdapy/engine.ini; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then pip install psycopg2 --use-mirrors; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then rm -rf ~/.xdapy; fi"

